palette = 0=#dee2ef
palette = 1=#ba1a1a
palette = 2=#005fb0
palette = 3=#5d598a
palette = 4=#001c3b
palette = 5=#555d7e
palette = 6=#121a37
palette = 7=#424751
palette = 8=#727782
palette = 9=#410002
palette = 10=#001c3b
palette = 11=#191443
palette = 12=#005fb0
palette = 13=#121a37
palette = 14=#555d7e
palette = 15=#171c24

background = #f9f9ff
foreground = #171c24
cursor-color = #171c24
cursor-text = #424751
selection-background = #bdc5eb
selection-foreground = #ffffff
