$image = /home/alex/Pictures/Wallpapers/8191_white-device_2560x1600.jpg

$background = rgba(f9f9ffff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(ecf1fdff)

$inverse_primary = rgba(a6c8ffff)

$inverse_surface = rgba(2b313aff)

$on_background = rgba(171c24ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(001c3bff)

$on_primary_fixed = rgba(001c3bff)

$on_primary_fixed_variant = rgba(004787ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(121a37ff)

$on_secondary_fixed = rgba(121a37ff)

$on_secondary_fixed_variant = rgba(3e4565ff)

$on_surface = rgba(171c24ff)

$on_surface_variant = rgba(424751ff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(191443ff)

$on_tertiary_fixed = rgba(191443ff)

$on_tertiary_fixed_variant = rgba(454171ff)

$outline = rgba(727782ff)

$outline_variant = rgba(c2c6d2ff)

$primary = rgba(005fb0ff)

$primary_container = rgba(d5e3ffff)

$primary_fixed = rgba(d5e3ffff)

$primary_fixed_dim = rgba(a6c8ffff)

$scrim = rgba(000000ff)

$secondary = rgba(555d7eff)

$secondary_container = rgba(dce1ffff)

$secondary_fixed = rgba(dce1ffff)

$secondary_fixed_dim = rgba(bdc5ebff)

$shadow = rgba(000000ff)

$source_color = rgba(6a7c9aff)

$surface = rgba(f9f9ffff)

$surface_bright = rgba(f9f9ffff)

$surface_container = rgba(e9eefaff)

$surface_container_high = rgba(e4e8f4ff)

$surface_container_highest = rgba(dee2efff)

$surface_container_low = rgba(f0f3ffff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(d6dae6ff)

$surface_tint = rgba(005fb0ff)

$surface_variant = rgba(dee2efff)

$tertiary = rgba(5d598aff)

$tertiary_container = rgba(e4dfffff)

$tertiary_fixed = rgba(e4dfffff)

$tertiary_fixed_dim = rgba(c6c0f9ff)

