monitor=,2560x1600@240Hz,0x0,1
general {
  gaps_in = 8
  gaps_out = 4
  border_size = 2
  col.active_border = rgb(0,0,0) rgb(0,0,0) 45deg
  col.inactive_border = rgba(595959aa)
  resize_on_border = true
  allow_tearing = false
  layout = dwindle
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  vrr = 0
  vfr = true
}
render {
  direct_scanout = 2
  cm_enabled = true
}

# experimental {
#   xx_color_management_v4 = true
# }
