source = /home/alex/.config/hypr/colors.conf
source = /home/alex/.config/hypr/programs.conf
source = /home/alex/.config/hypr/appearance.conf
source = /home/alex/.config/hypr/display.conf
source = /home/alex/.config/hypr/input.conf
source = /home/alex/.config/hypr/keybinds.conf
source = /home/alex/.config/hypr/startup.conf
source = /home/alex/.config/hypr/windowrules.conf
