exec-once = $bar
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = NVD_BACKEND,direct
env = XDG_MENU_PREFIX,arch-
exec-once = kbuildsycoca6
exec-once=walker --gapplication-service
env = QT_QPA_PLATFORMTHEME,hyprqt6engine
env = PROTON_ENABLE_WAYLAND,1
env = PROTON_DLSS_UPGRADE,1
env = PROTON_NVIDIA_LIBS,1
env = PROTON_USE_NTSYNC,1
env = WINE_DISABLE_VULKAN_OPWR,1
